<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Mir-PC" ignored="0" name="Test" tests="3" failures="1" timestamp="23 Sep 2020 05:58:37 GMT" time="59.416" errors="0">
  <testcase name="verifyLoginPageText" time="2.234" classname="retry_FinalTests.TestNGExampleTests">
    <skipped/>
  </testcase> <!-- verifyLoginPageText -->
  <testcase name="verifyLoginPageText" time="2.7" classname="retry_FinalTests.TestNGExampleTests">
    <failure type="java.lang.AssertionError" message="Forced to fail">
      <![CDATA[java.lang.AssertionError: Forced to fail
at retry_FinalTests.TestNGExampleTests.verifyLoginPageText(TestNGExampleTests.java:48)
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- verifyLoginPageText -->
  <testcase name="verifyForgotPasswordPage" time="7.002" classname="retry_FinalTests.TestNGExampleTests"/>
</testsuite> <!-- Test -->
