<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Mir-PC" ignored="0" name="Test" tests="9" failures="2" timestamp="20 Sep 2020 03:05:13 GMT" time="0.157" errors="0">
  <testcase name="login1" time="0.028" classname="login.CreateLogin">
    <skipped/>
  </testcase> <!-- login1 -->
  <testcase name="login1" time="0.004" classname="login.CreateLogin">
    <skipped/>
  </testcase> <!-- login1 -->
  <testcase name="login1" time="0.004" classname="login.CreateLogin">
    <skipped/>
  </testcase> <!-- login1 -->
  <testcase name="login1" time="0.003" classname="login.CreateLogin">
    <failure type="java.lang.AssertionError" message="Forced to fail">
      <![CDATA[java.lang.AssertionError: Forced to fail
at login.CreateLogin.login1(CreateLogin.java:12)
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- login1 -->
  <testcase name="login2" time="0.002" classname="login.CreateLogin"/>
  <testcase name="login3" time="0.007" classname="login.CreateLogin">
    <skipped/>
  </testcase> <!-- login3 -->
  <testcase name="login3" time="0.003" classname="login.CreateLogin">
    <skipped/>
  </testcase> <!-- login3 -->
  <testcase name="login3" time="0.003" classname="login.CreateLogin">
    <skipped/>
  </testcase> <!-- login3 -->
  <testcase name="login3" time="0.004" classname="login.CreateLogin">
    <failure type="java.lang.AssertionError" message="Forced to fail">
      <![CDATA[java.lang.AssertionError: Forced to fail
at login.CreateLogin.login3(CreateLogin.java:23)
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- login3 -->
</testsuite> <!-- Test -->
